language: minimal

services: docker

branches:
  only:
    - master

env:
  # BUILD, DEPLOY, RELEASE, RELEASE-BETA,  
  - ACTION='BUILD' VERSION= ROLLBACK_VERSION=

before_install:
  - bash ./scripts/build.sh $ACTION
  - bash ./scripts/deploy.sh $ACTION, $VERSION, $ROLLBACK_VERSION

install:
  - bash ./scripts/release.sh $ACTION, $VERSION, $ROLLBACK_VERSION

