language: minimal

services: docker

branches:
  only:
    - master

env:
  # BUILD, DEPLOY, RELEASE, RELEASE-BETA,  
  - ACTION='BUILD' VERSION= ROLLBACK_VERSION=

before_install:
  - ./scripts/build.sh $ACTION
  - ./scripts/deploy.sh $ACTION, $VERSION, $ROLLBACK_VERSION

install:
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./scripts/release.sh $ACTION, $VERSION, $ROLLBACK_VERSION; fi'

