language: minimal

services: docker

branches:
  only:
    - master

env:
  # ACTION: BUILD, DEPLOY, RELEASE, RELEASE-BETA, ROLLBACK, ROLLBACK-BETA  
  - ACTION=RELEASE-BETA VERSION=1.1 ROLLBACK_VERSION=1.0

before_install:
  - bash ./scripts/build.sh $ACTION $VERSION
  - bash ./scripts/deploy.sh $ACTION $VERSION $ROLLBACK_VERSION

install:
  - bash ./scripts/release.sh $ACTION $VERSION $ROLLBACK_VERSION

