language: minimal

services: docker

branches:
  only:
    - master

env:
  # BUILD, DEPLOY, RELEASE, RELEASE-BETA,  
  - ACTION='BUILD' VERSION= ROLLBACK_VERSION=

before_install:
  script: scripts/build.sh $ACTION
  script: scripts/deploy.sh $ACTION, $VERSION, $ROLLBACK_VERSION

install:
  script: scripts/release.sh $ACTION, $VERSION, $ROLLBACK_VERSION

